semi: false
singleQuote: true
trailingComma: all
tabWidth: 4
bracketSpacing: true
overrides:
  - files:
      - '*.js'
    options:
      parser: babylon
  - files:
      - '*.ts'
      - '*.tsx'
    options:
      parser: typescript
  - files:
      - '*.json'
      - '*.yml'
      - '*.yaml'
    options:
      parser: json
